### PR TITLE
Render regions too, and support for blaze-integration branch of iron-router

### PR DESCRIPTION
**Pull request by zimme**

### CODE REVIEW

**Comment by xpressivecode** [comment]
@zimme will this cause any issues for people not using the blaze rc?

**Comment by zimme** [comment]
I don't think there should be any problems for people that isn't using blaze but i believe there will be a problem if they aren't using the blaze-integration branch of iron-router as that's where this.stop() is changed to pause() and yields are regions

**Comment by xpressivecode** [comment]
Ok, I'll create a new blaze branch later on and merge your fixes in. Appreciate the pull request. Afterwards I'll see if I can replicate the issue you're having in the other ticket and fix it.

**Comment by xpressivecode** [comment]
hi @zimme thanks for this! appreciate the time and contribution.

**Pull request merged**
